package com.example.myplayer.db;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig memoDaoConfig;
    private final DaoConfig memo_extraDaoConfig;

    private final MemoDao memoDao;
    private final Memo_extraDao memo_extraDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        memoDaoConfig = daoConfigMap.get(MemoDao.class).clone();
        memoDaoConfig.initIdentityScope(type);

        memo_extraDaoConfig = daoConfigMap.get(Memo_extraDao.class).clone();
        memo_extraDaoConfig.initIdentityScope(type);

        memoDao = new MemoDao(memoDaoConfig, this);
        memo_extraDao = new Memo_extraDao(memo_extraDaoConfig, this);

        registerDao(Memo.class, memoDao);
        registerDao(Memo_extra.class, memo_extraDao);
    }

    public void clear() {
        memoDaoConfig.clearIdentityScope();
        memo_extraDaoConfig.clearIdentityScope();
    }

    public MemoDao getMemoDao() {
        return memoDao;
    }

    public Memo_extraDao getMemo_extraDao() {
        return memo_extraDao;
    }

}
